# Generated by Django 4.2.11 on 2024-05-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starting', '0002_food_user1_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
    ]
