# Generated by Django 4.2.11 on 2024-05-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starting', '0003_alter_reservation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reservation_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reservation_vip',
                'managed': False,
            },
        ),
    ]
