# Generated by Django 4.2.11 on 2024-07-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starting', '0004_reservationtable_reservationvip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
