# Generated by Django 4.2.11 on 2024-07-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starting', '0005_delete_user_delete_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationTable',
        ),
        migrations.DeleteModel(
            name='ReservationVip',
        ),
    ]
