# Generated by Django 5.1.1 on 2024-10-28 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomMenu',
            fields=[
                ('name', models.CharField(default='Custom Menu', max_length=256)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 10, 28, 22, 13, 22, 210463, tzinfo=datetime.timezone.utc))),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomMenuDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_menu', models.ManyToManyField(to='user_profile.usercustommenu')),
            ],
        ),
    ]
