# Generated by Django 5.1.1 on 2024-10-29 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommenu',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 8, 51, 44, 370024, tzinfo=datetime.timezone.utc)),
        ),
    ]
