# Generated by Django 5.1.1 on 2024-11-07 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0008_delete_foodcombo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('start_time', models.DateTimeField(verbose_name='Start Date')),
                ('end_time', models.DateTimeField(verbose_name='End Date')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('discount_type', models.CharField(choices=[('FLAT', 'Flat'), ('PERCENTAGE', 'Percentage')], default='FLAT', max_length=20, verbose_name='Discount Type')),
                ('amount', models.CharField(default='25000', max_length=20, verbose_name='Amount Reduced')),
                ('food', models.ManyToManyField(to='base.food', verbose_name='promotion_foods')),
            ],
        ),
        migrations.CreateModel(
            name='UserPromotions',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.promotion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
