# Generated by Django 5.1.1 on 2024-11-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_foodcombo'),
        ('promotion', '0003_alter_promotion_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='food',
            field=models.ManyToManyField(to='base.food', verbose_name='promotion_foods'),
        ),
    ]
