# Generated by Django 5.1.1 on 2024-11-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_alter_promotion_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='food',
            new_name='foods',
        ),
        migrations.AddField(
            model_name='promotion',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Creation Date'),
        ),
    ]
