# Generated by Django 5.1.1 on 2024-11-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_food_num_of_rating_food_rating'),
        ('promotion', '0005_rename_food_promotion_foods_promotion_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='foods',
        ),
        migrations.CreateModel(
            name='Promotion_FoodFK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.food', verbose_name='')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.promotion', verbose_name='Promotion')),
            ],
        ),
    ]
