# Generated by Django 5.1.1 on 2024-11-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_food_num_of_rating_food_rating'),
        ('promotion', '0006_remove_promotion_foods_promotion_foodfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='foods',
            field=models.ManyToManyField(through='promotion.Promotion_FoodFK', to='base.food', verbose_name='promotion_foods'),
        ),
    ]
