# Generated by Django 5.1.1 on 2024-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_promotion_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is Visible'),
        ),
        migrations.AddField(
            model_name='userpromotion',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50, verbose_name='Status'),
        ),
    ]
