# Generated by Django 5.1.1 on 2024-12-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_delete_foodpromotion'),
        ('promotion', '0008_promotion_is_visible_userpromotion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion_foodfk',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.food', verbose_name='Food'),
        ),
    ]
