# Generated by Django 5.1.1 on 2024-10-31 08:42

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_alter_food_ingredient'),
        ('restaurant', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(error_messages={'unique': 'This phone number is already in use.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Wrong number format entered', regex='^0[19]\\d{8}$')])),
                ('price', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10)),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 11, 3, 8, 42, 1, 70588, tzinfo=datetime.timezone.utc))),
                ('eat_time', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished')], default='FINISHED', max_length=20, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('table', models.ManyToManyField(related_name='tables', to='restaurant.restauranttable')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vip', models.ManyToManyField(related_name='vips', to='restaurant.restaurantvip')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationCombo_FK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField()),
                ('combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.foodcombo')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='combo',
            field=models.ManyToManyField(related_name='combos', through='reservation.ReservationCombo_FK', to='base.foodcombo'),
        ),
        migrations.CreateModel(
            name='ReservationFood_FK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField()),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.food')),
                ('ordering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='food',
            field=models.ManyToManyField(related_name='foods', through='reservation.ReservationFood_FK', to='base.food'),
        ),
    ]
