# Generated by Django 5.1.1 on 2024-10-31 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 9, 1, 57, 999176, tzinfo=datetime.timezone.utc)),
        ),
    ]
