# Generated by Django 5.1.1 on 2024-10-31 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 9, 3, 18, 867619, tzinfo=datetime.timezone.utc)),
        ),
    ]
