# Generated by Django 5.1.1 on 2024-10-31 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 16, 50, 12, 9836, tzinfo=datetime.timezone.utc)),
        ),
    ]
