# Generated by Django 5.1.1 on 2024-10-31 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='combo',
            new_name='combos',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='food',
            new_name='foods',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='table',
            new_name='tables',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='vip',
            new_name='vips',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 18, 25, 48, 804241, tzinfo=datetime.timezone.utc)),
        ),
    ]
