# Generated by Django 5.1.1 on 2024-10-31 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_rename_combo_reservation_combos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 18, 31, 53, 141204, tzinfo=datetime.timezone.utc)),
        ),
    ]
