# Generated by Django 5.1.1 on 2024-11-07 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 6, 11, 12, 261113, tzinfo=datetime.timezone.utc)),
        ),
    ]
