# Generated by Django 5.1.1 on 2024-11-07 22:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_combotype_remove_foodcombo_foods_and_more'),
        ('reservation', '0008_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='combos',
            field=models.ManyToManyField(related_name='combos', through='reservation.ReservationCombo_FK', to='base.combo'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 22, 36, 48, 424049, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservationcombo_fk',
            name='combo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.combo'),
        ),
    ]
