# Generated by Django 5.1.1 on 2024-11-07 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 23, 6, 48, 801558, tzinfo=datetime.timezone.utc)),
        ),
    ]
