# Generated by Django 5.1.1 on 2024-11-14 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 10, 45, 33, 407983, tzinfo=datetime.timezone.utc)),
        ),
    ]
