# Generated by Django 5.1.1 on 2024-11-15 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 3, 23, 3, 839789, tzinfo=datetime.timezone.utc)),
        ),
    ]
