# Generated by Django 5.1.1 on 2024-11-21 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 12, 53, 34, 931592, tzinfo=datetime.timezone.utc)),
        ),
    ]
