# Generated by Django 5.1.1 on 2024-11-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_alter_reservation_date_created_and_more'),
        ('restaurant', '0004_alter_restaurant_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationfood_fk',
            old_name='ordering',
            new_name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
