# Generated by Django 5.1.1 on 2024-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_rename_ordering_reservationfood_fk_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
