# Generated by Django 5.1.1 on 2024-10-31 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_alter_ordering_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 9, 3, 18, 869617, tzinfo=datetime.timezone.utc)),
        ),
    ]
