# Generated by Django 5.1.1 on 2024-10-31 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_alter_ordering_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 16, 50, 12, 11837, tzinfo=datetime.timezone.utc)),
        ),
    ]
