# Generated by Django 5.1.1 on 2024-11-05 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_alter_ordering_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 0, 44, 59, 315444, tzinfo=datetime.timezone.utc)),
        ),
    ]
