# Generated by Django 5.1.1 on 2024-11-07 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_alter_ordering_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 6, 11, 12, 272131, tzinfo=datetime.timezone.utc)),
        ),
    ]
