# Generated by Django 5.1.1 on 2024-11-07 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_remove_ordering_combo_alter_ordering_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 22, 51, 37, 506144, tzinfo=datetime.timezone.utc)),
        ),
    ]
