# Generated by Django 5.1.1 on 2024-11-07 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0011_alter_ordering_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 23, 6, 48, 803557, tzinfo=datetime.timezone.utc)),
        ),
    ]
