# Generated by Django 5.1.1 on 2024-11-13 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0012_alter_ordering_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 23, 49, 3, 876890, tzinfo=datetime.timezone.utc)),
        ),
    ]
