# Generated by Django 5.1.1 on 2024-11-14 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0013_alter_ordering_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 10, 44, 6, 543649, tzinfo=datetime.timezone.utc)),
        ),
    ]
