# Generated by Django 5.1.1 on 2024-11-21 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0016_alter_ordering_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordering',
            old_name='time',
            new_name='delivery_time',
        ),
        migrations.AddField(
            model_name='ordering',
            name='user_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 12, 53, 34, 940968, tzinfo=datetime.timezone.utc)),
        ),
    ]
