# Generated by Django 5.1.1 on 2024-11-21 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0017_rename_time_ordering_delivery_time_and_more'),
        ('payment', '0005_alter_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPING', 'Shipping'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
