# Generated by Django 5.1.1 on 2024-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0019_alter_ordering_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='bill_url',
            field=models.URLField(null=True, verbose_name='Bill Url'),
        ),
    ]
