// THIS IS DEFAULT PARAMETERS THAT CAN BE EASILY FOUND ON THE INTERNET
// PLEASE DO THE REQUIRED BUSINESS PROCESS FOR YOUR OWN PARAMETERS

export const momo = {
  accessKey: "F8BBA842ECF85",
  secretKey: "K951B6PE1waDMi640xX08PD3vg6EkVlz",
  orderInfo: "pay with MoMo",
  partnerCode: "MOMO",
};
