export const MENU_LIST_REQUEST = "MENU_LIST_REQUEST";
export const MENU_LIST_SUCCESS = "MENU_LIST_SUCCESS";
export const MENU_LIST_FAIL = "MENU_LIST_FAIL";

export const MENU_ITEM_REQUEST = "MENU_ITEM_REQUEST";
export const MENU_ITEM_SUCCESS = "MENU_ITEM_SUCCESS";
export const MENU_ITEM_FAIL = "MENU_ITEM_FAIL";
