# Generated by Django 5.1.1 on 2024-10-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('count_in_stock', models.IntegerField(default=0, null=True)),
                ('nutrition_value', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('num_ppl_eat', models.IntegerField(blank=True, default=1, null=True)),
                ('is_hot', models.BooleanField(default=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('num_of_rating', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPromotion',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('amount_percentage', models.IntegerField(default=0, null=True)),
                ('amount_value', models.IntegerField(default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomMenu',
            fields=[
                ('name', models.CharField(default='User', max_length=256, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commenter_name', models.CharField(default='Commenter', max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('like_reaction', models.IntegerField(blank=True, default=0, null=True)),
                ('dislike_reaction', models.IntegerField(blank=True, default=0, null=True)),
                ('star_rating', models.DecimalField(decimal_places=0, max_digits=2)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reply_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.comment')),
                ('food_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCombo',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('food', models.ManyToManyField(to='base.food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='ingredient',
            field=models.ManyToManyField(blank=True, default='', to='base.foodingredient'),
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('rating', models.DecimalField(decimal_places=0, default=0.0, max_digits=2)),
                ('description', models.TextField(default='')),
                ('time_upload', models.DateTimeField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.food')),
            ],
        ),
    ]
