# Generated by Django 5.1.1 on 2024-10-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_food_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='FoodComment',
        ),
        migrations.AddField(
            model_name='foodcomboitem',
            name='qty',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='foodcombo',
            name='count_in_stock',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
