# Generated by Django 5.1.1 on 2024-09-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_foodingredient_foodtag_foodtype_food_count_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_tag',
            field=models.ManyToManyField(blank=True, null=True, to='base.foodtag'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredient',
            field=models.ManyToManyField(blank=True, null=True, to='base.foodingredient'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
