# Generated by Django 5.1.1 on 2024-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_comment_foodcomment_foodcomboitem_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcombo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
