# Generated by Django 5.1.1 on 2024-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_food_food_tag_alter_food_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='number_people_eating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
