# Generated by Django 5.1.1 on 2024-10-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_foodcombo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcombo',
            old_name='food',
            new_name='foods',
        ),
    ]
