# Generated by Django 5.1.1 on 2024-11-05 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_food_foodcombo_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcombo',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.foodtype'),
        ),
        migrations.AddField(
            model_name='foodcombo',
            name='ingredient',
            field=models.ManyToManyField(editable=False, to='base.foodingredient'),
        ),
        migrations.AddField(
            model_name='foodcombo',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodcombo',
            name='tag',
            field=models.ManyToManyField(editable=False, to='base.foodtag'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredients', to='base.foodingredient'),
        ),
        migrations.AlterField(
            model_name='foodcombo',
            name='count_in_stock',
            field=models.IntegerField(default=10, editable=False),
        ),
        migrations.DeleteModel(
            name='ComboType',
        ),
    ]
