# Generated by Django 5.1.1 on 2024-10-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_food_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='num_of_rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='count_in_stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commenter_name', models.CharField(default='Commenter', max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('like_reaction', models.IntegerField(blank=True, default=0, null=True)),
                ('dislike_reaction', models.IntegerField(blank=True, default=0, null=True)),
                ('star_rating', models.DecimalField(decimal_places=0, max_digits=2)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.foodtype')),
                ('reply_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.comment')),
            ],
        ),
    ]
