# Generated by Django 5.1.1 on 2024-10-09 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_food_num_of_rating_food_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCombo',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPromotion',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('amount_percentage', models.IntegerField(default=0, null=True)),
                ('amount_value', models.IntegerField(default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='food_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base.foodtype'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_tag',
            field=models.ManyToManyField(blank=True, to='base.foodtag'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='base.foodingredient'),
        ),
    ]
