# Generated by Django 5.1.1 on 2024-10-09 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_foodcombo_foodpromotion_alter_comment_food_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='food_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base.food'),
        ),
    ]
