# Generated by Django 5.1.1 on 2024-11-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_combotype_remove_foodcombo_foods_and_more'),
        ('ordering', '0009_remove_ordering_combo_alter_ordering_date_created_and_more'),
        ('reservation', '0009_alter_reservation_combos_alter_reservation_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCombo',
        ),
    ]
