# Generated by Django 5.1.1 on 2024-10-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_food_is_hot_alter_comment_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
