# Generated by Django 5.1.1 on 2024-11-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_foodcombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='num_of_rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
