# Generated by Django 5.1.1 on 2024-10-20 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_food_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_tag',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='food',
            name='number_people_eating',
        ),
        migrations.AddField(
            model_name='food',
            name='num_ppl_eat',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='base.foodtag'),
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='base.foodtype'),
        ),
        migrations.AddField(
            model_name='foodcombo',
            name='food',
            field=models.ManyToManyField(to='base.food'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.comment'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredient',
            field=models.ManyToManyField(blank=True, default='', to='base.foodingredient'),
        ),
        migrations.AlterField(
            model_name='food',
            name='nutrition_value',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.food')),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomMenu',
            fields=[
                ('name', models.CharField(default='User', max_length=256, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
