# Generated by Django 5.1.1 on 2024-12-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_combo_image_alter_food_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodPromotion',
        ),
    ]
