# Generated by Django 5.1.1 on 2024-12-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_delete_foodpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcomment',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
