# Generated by Django 5.1.1 on 2024-10-28 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('hotline', models.CharField(default='0101010101', max_length=10, validators=[django.core.validators.RegexValidator(message='Wrong number format entered', regex='^0[19]\\d{8}$')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=0, default=0.0, editable=False, max_digits=2)),
                ('num_of_rating', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('score', models.DecimalField(decimal_places=0, max_digits=1)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantVIP',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
