# Generated by Django 5.1.1 on 2024-10-31 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_options_alter_restaurant_manager'),
        ('users', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.manager'),
        ),
    ]
