# Generated by Django 4.2.11 on 2024-07-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('nutrition_value', models.TextField(blank=True, null=True)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_num', models.IntegerField(blank=True, null=True)),
                ('eat_time', models.DateTimeField(blank=True, null=True)),
                ('num_of_people', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reservation_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reservation_vip',
                'managed': False,
            },
        ),
    ]
