# Generated by Django 5.1.1 on 2024-10-30 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=models.CharField(error_messages={'unique': 'This phone number is already in use.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Wrong number format entered', regex='^0[19]\\d{8}$')]), max_length=50, null=True),
        ),
    ]
