# Generated by Django 5.1.1 on 2024-10-30 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 7, 58, 13, 332536, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
