# Generated by Django 5.1.1 on 2024-12-06 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_delete_foodpromotion'),
        ('users', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomMenu',
            fields=[
                ('name', models.CharField(default='Custom Menu', max_length=256)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nutrition_value', models.TextField(null=True)),
                ('num_ppl_eating', models.IntegerField(default=1, verbose_name='Number of people eating')),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomMenuDetailsCombo_FK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, verbose_name='Quantity')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.combo')),
                ('custom_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usercustommenu')),
            ],
        ),
        migrations.AddField(
            model_name='usercustommenu',
            name='combos',
            field=models.ManyToManyField(related_name='custommenucombo_set', through='users.UserCustomMenuDetailsCombo_FK', to='base.combo', verbose_name='combo_list'),
        ),
        migrations.CreateModel(
            name='UserCustomMenuDetailsFood_FK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, verbose_name='Quantity')),
                ('custom_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usercustommenu')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.food')),
            ],
        ),
        migrations.AddField(
            model_name='usercustommenu',
            name='foods',
            field=models.ManyToManyField(related_name='custommenufood_set', through='users.UserCustomMenuDetailsFood_FK', to='base.food', verbose_name='food_list'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usercustommenu',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
