# Generated by Django 5.1.1 on 2024-10-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_admin_customer_manager_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20, verbose_name='Role'),
        ),
    ]
