# Generated by Django 5.1.1 on 2024-10-22 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_is_active_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'This phone number is already in use.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Wrong number format entered', regex='^0[19]\\d{8}$')]),
        ),
    ]
